### ISSUE TITLE
Systemd service-name does not respect variant `name` option

### ISSUE THREAD

**Issue by brocaar** [kornelski/cargo-deb#150]
I have a similar use-case as #86. I have one package for which I would like to distribute two versions. Example:

```toml
    [package.metadata.deb.variants.postgres]
      name = "example"

    [package.metadata.deb.variants.sqlite]
      example = "example-sqlite"
```

This correctly generates two `.deb` packages named:

* `example` and
* `example-sqlite`

However, it generates two systemd services:

* `example-postgres`
* `example-sqlite`

Expected behavor:

I would expect `example` and `example-sqlite` as systemd service-names.
