### ISSUE TITLE
Change location of files based on arch

### ISSUE THREAD

**Issue by drgoochifer** [kornelski/cargo-deb#174]
I'd like to change the location of files in a `.deb` package based on the architecture.  I'm not seeing the file locations change when overriding using `[package.metadata.deb.variants.arm64]`.  I'm also not sure how to refer to the `copyright` file that's created in `/usr/share/doc/testcli/` so I can change its location as well.  Any help would be appreciated.

```
[[bin]]
name = "testcli"
path = "src/main.rs"

[package.metadata.deb]
maintainer = "<Example Dev> example-dev@example.com"
copyright = "2025 Example Copyright"
depends = ""
priority = "required"

[package.metadata.deb.variants.arm64]
assets = [
  { source = "target/release/testcli", dest = "/etc/bin/", mode = "755" },
  { source = "README.md", dest = "/opt/testcli/share/doc/README.md", mode = "644" },
]
```

**Comment by kornelski** [comment]
What paths do you expect?

**Comment by npapapietro** [comment]
I second this, I have some examples where I have dynamic linked libs that need to be bundled.

I should be able to do something like 
```toml
[target.'cfg(target_arch  = "aarch64")'.package.metadata.deb]
assets=[{source="deps/aarch64/*", dest="/usr/lib", mode="644"}]

[target.'cfg(target_arch  = "x86_64")'.package.metadata.deb]
assets=[{source="deps/x86_64/*", dest="/usr/lib", mode="644"}]
```
