### ISSUE TITLE
Error: on profile.release using "symbols" 

### ISSUE THREAD

**Issue by Corfucinas** [kornelski/cargo-deb#22]
With [Rust 1.59](https://blog.rust-lang.org/2022/02/24/Rust-1.59.0.html) it is possible to use on stable 

```toml
[profile.release]
strip = "symbols"
```

This is equivalent to 

```toml
[profile.release]
strip = true
```

However, if somebody uses an option that is no a boolean, the following error will appear

```text
cargo-deb: unable to parse Cargo.toml
  because: invalid type: string "symbols", expected a boolean for key `profile.release.strip` at line 34 column 9
```

```text
cargo deb --version
1.36.0
```
