### ISSUE TITLE
Warn on nonexistent file listed as an asset

### ISSUE THREAD

**Issue by sburris0** [kornelski/cargo-deb#30]
If a user lists a nonexistent file as an asset, it would be very helpful to get a warning about it.

e.g.
```toml
[package.metadata.deb.variants.debug]
assets =  [
    ["dir/fake_file.txt", "/var/log", "755"],
]
```

might yield
`Warning: 'dir/fake_file.txt' does not exist and will not be added to deb`

Missing `unit-names` would also be nice, while trying to use a systemd service template it wasn't obvious to exlude the @
