### ISSUE TITLE
Add support for multiple systemd file

### ISSUE THREAD

**Issue by samdolt** [kornelski/cargo-deb#42]
After looking at the code and the source, it seems like it's not possible to provide multiple service file. As a package can provide multiple binaries, it can be usefull to have support for multiple service too.

Maybe by using somethings like that in Cargo.toml:

```toml
[package.metadata.deb]
maintainer-scripts = "debian/"

[package.metadata.deb.systemd-units]
enable = false
unit-names = ["binaryname1", "binaryname2"]
```
